import { CharacterClass } from "@/types/game";
import { ClassConfig } from "./types";

export const CLASS_CONFIGS: Record<CharacterClass, ClassConfig> = {
  knight: {
    id: "knight",
    label: "Knight",
    weaponType: "sword",
    offhand: "shield",
    armorWeight: "heavy",
    headgear: "none",
    capeStyle: "short",
    colors: {
      primary: "#7B8D9E",
      primaryDark: "#4A5A6A",
      secondary: "#6A5A4A",
      accent: "#C0A030",
      pantsColor: "#3B2F2F",
      bootColor: "#4A3A2A",
      bootTrim: "#8B6914",
      capeColor: "#3A4A5A",
      capeBorder: "#2A3A4A",
      armorMetalness: 0.7,
      armorRoughness: 0.3,
    },
  },

  paladin: {
    id: "paladin",
    label: "Paladin",
    weaponType: "sword",
    offhand: "shield",
    armorWeight: "heavy",
    headgear: "none",
    capeStyle: "long",
    colors: {
      primary: "#E8E0D0",
      primaryDark: "#C8C0B0",
      secondary: "#DAA520",
      accent: "#FFD700",
      pantsColor: "#4A4040",
      bootColor: "#5C4A3A",
      bootTrim: "#DAA520",
      capeColor: "#E0D8C8",
      capeBorder: "#DAA520",
      armorMetalness: 0.65,
      armorRoughness: 0.25,
    },
  },

  rogue: {
    id: "rogue",
    label: "Rogue",
    weaponType: "dagger",
    offhand: "none",
    armorWeight: "light",
    headgear: "hood",
    capeStyle: "light",
    colors: {
      primary: "#5C4A32",
      primaryDark: "#3A3020",
      secondary: "#3A5A3A",
      accent: "#8B6914",
      pantsColor: "#3A3020",
      bootColor: "#4A3A28",
      bootTrim: "#5C4A32",
      capeColor: "#3A3020",
      capeBorder: "#2A2018",
      armorMetalness: 0.15,
      armorRoughness: 0.75,
    },
  },

  assassin: {
    id: "assassin",
    label: "Assassin",
    weaponType: "katar",
    offhand: "none",
    armorWeight: "light",
    headgear: "mask",
    capeStyle: "none",
    colors: {
      primary: "#1A1A2E",
      primaryDark: "#0E0E1A",
      secondary: "#4A2060",
      accent: "#8B0000",
      pantsColor: "#1A1A1A",
      bootColor: "#1A1A1A",
      bootTrim: "#4A2060",
      capeColor: "#1A1A2E",
      capeBorder: "#0E0E1A",
      armorMetalness: 0.2,
      armorRoughness: 0.6,
    },
  },

  ranger: {
    id: "ranger",
    label: "Ranger",
    weaponType: "bow",
    offhand: "none",
    armorWeight: "medium",
    headgear: "none",
    capeStyle: "none",
    colors: {
      primary: "#4A6A3A",
      primaryDark: "#2A4A22",
      secondary: "#6B4226",
      accent: "#8B7355",
      pantsColor: "#3A3020",
      bootColor: "#5C3A1E",
      bootTrim: "#6B4226",
      capeColor: "#3A5A2A",
      capeBorder: "#2A4A1A",
      armorMetalness: 0.1,
      armorRoughness: 0.8,
    },
  },

  wizard: {
    id: "wizard",
    label: "Wizard",
    weaponType: "staff",
    offhand: "none",
    armorWeight: "cloth",
    headgear: "wizard_hat",
    capeStyle: "none",
    colors: {
      primary: "#2244AA",
      primaryDark: "#1A2A6E",
      secondary: "#1A1A5E",
      accent: "#C0A030",
      pantsColor: "#1A2A5E",
      bootColor: "#3A2A1E",
      bootTrim: "#C0A030",
      capeColor: "#1A2A6E",
      capeBorder: "#C0A030",
      armorMetalness: 0.05,
      armorRoughness: 0.9,
    },
  },

  sorcerer: {
    id: "sorcerer",
    label: "Sorcerer",
    weaponType: "staff",
    offhand: "book",
    armorWeight: "cloth",
    headgear: "none",
    capeStyle: "long",
    colors: {
      primary: "#6A2C91",
      primaryDark: "#4A1A6A",
      secondary: "#DAA520",
      accent: "#FFD700",
      pantsColor: "#3A1A4A",
      bootColor: "#4A2A3A",
      bootTrim: "#DAA520",
      capeColor: "#4A1A6A",
      capeBorder: "#DAA520",
      armorMetalness: 0.1,
      armorRoughness: 0.85,
    },
  },

  priest: {
    id: "priest",
    label: "Priest",
    weaponType: "staff",
    offhand: "none",
    armorWeight: "cloth",
    headgear: "none",
    capeStyle: "short",
    colors: {
      primary: "#F0E8D8",
      primaryDark: "#D0C8B8",
      secondary: "#DAA520",
      accent: "#FFD700",
      pantsColor: "#C8C0B0",
      bootColor: "#5C4A3A",
      bootTrim: "#DAA520",
      capeColor: "#E0D8C8",
      capeBorder: "#DAA520",
      armorMetalness: 0.05,
      armorRoughness: 0.9,
    },
  },

  monk: {
    id: "monk",
    label: "Monk",
    weaponType: "fists",
    offhand: "none",
    armorWeight: "cloth",
    headgear: "headband",
    capeStyle: "none",
    colors: {
      primary: "#D4A574",
      primaryDark: "#B08050",
      secondary: "#8B6914",
      accent: "#C0A030",
      pantsColor: "#8B6914",
      bootColor: "#6B4226",
      bootTrim: "#8B6914",
      capeColor: "#B08050",
      capeBorder: "#8B6914",
      armorMetalness: 0.0,
      armorRoughness: 0.95,
    },
  },
};

export function getClassConfig(characterClass: CharacterClass): ClassConfig {
  return CLASS_CONFIGS[characterClass];
}
